services:
  - type: web
    name: oscode-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URL
        fromService:
          type: pserv
          name: mongodb
          property: connectionString

databases:
  - name: mongodb
    databaseName: oscode_platform
    plan: free